language: node_js
node_js:
  - 8

cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: test
      script: npm run lint
    - script: npm run test
    - stage: coverage
      script: npm run coverage
